### PR TITLE
[build] build codecs for aarch64

### PR DESCRIPTION
**Pull request by jlaine**

### CODE REVIEW

**Comment by odidev** [comment]
@jlaine, I have tested the steps on Linux AArch64 machine and it look to be working fine. You push a dummy commit to re-trigger the build.

**Comment by jlaine** [comment]
I have really had no luck with `aarch64` builds, qemu seems to be locking up or exceeding the limits allowed by GitHub actions. The same thing is holding up providing binary wheels for `PyAV`..

**Comment by jlaine** [comment]
I don't know yet if it's a fluke, but changing `make -j` to `make` allowed the build to succeed (it took one hour though!).

**Comment by odidev** [comment]
@jlaine, thanks for your effort.

**Pull request merged**
